name: Deploy Crypto-QR.github.io

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Especificamos que usaremos una carpeta personalizada
          static_site_generator: "custom"
          
      - name: Upload artifact from encryption project
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta a tu carpeta con el proyecto
          path: './proyecto encrip'  # Nombre exacto de la carpeta con espacio
          
          # Configuración adicional para SPA
          retention-days: 1
          exclude_assets: |
            *.md
            .gitignore
            LICENSE
            .github

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
